import type { ElementDef } from "./types";

/**
 * All 118 known elements. `row`/`col` place each tile on the standard periodic
 * table grid (rows 8-9 are the lanthanide/actinide display rows). `shells` is
 * the electron count per shell (Bohr model). The ~24 elements with a `quiz`
 * field are hand-authored "featured" elements; everything else gets a
 * generated quiz from its own data (see quiz.ts).
 */
export const ELEMENTS: ElementDef[] = [
  {
    number: 1,
    symbol: "H",
    name: "Hydrogen",
    category: "nonmetal",
    row: 1,
    col: 1,
    shells: [1],
    facts: {
      discoveredYear: 1766,
      discoveredBy: "Henry Cavendish",
      usedIn: "Rocket fuel, ammonia production, and as the fuel in fuel-cell vehicles.",
      funFact: "It's the most abundant element in the universe — about 75% of all normal matter.",
    },
    quiz: {
      question: "What makes up most of the mass of the Sun?",
      options: ["Hydrogen", "Oxygen", "Helium", "Carbon"],
      correctIndex: 0,
      hint: "It's the lightest and most abundant element in the universe.",
    },
  },
  {
    number: 2,
    symbol: "He",
    name: "Helium",
    category: "noble-gas",
    row: 1,
    col: 18,
    shells: [2],
    facts: {
      discoveredYear: 1868,
      discoveredBy: "Pierre Janssen & Norman Lockyer",
      usedIn: "Party balloons, cooling MRI magnets, and deep-sea diving gas mixes.",
      funFact: "It was found in sunlight before it was ever found on Earth — hence the name, from Helios.",
    },
    quiz: {
      question: "Where is helium most commonly used?",
      options: [
        "Cooling MRI machine magnets",
        "Making steel harder",
        "Powering car batteries",
        "Fertilizing crops",
      ],
      correctIndex: 0,
      hint: "Hospitals rely on it to keep giant superconducting magnets extremely cold.",
    },
  },
  {
    number: 3,
    symbol: "Li",
    name: "Lithium",
    category: "alkali-metal",
    row: 2,
    col: 1,
    shells: [2, 1],
    facts: {
      discoveredYear: 1817,
      discoveredBy: "Johan August Arfwedson",
      usedIn: "Rechargeable batteries in phones, laptops, and electric cars.",
      funFact: "It's light enough to float on water — and reactive enough that you shouldn't try it.",
    },
    quiz: {
      question: "What everyday device is most likely to contain lithium?",
      options: ["A smartphone battery", "A cast-iron pan", "A glass window", "A rubber tire"],
      correctIndex: 0,
      hint: "Think about what powers your phone overnight.",
    },
  },
  {
    number: 4,
    symbol: "Be",
    name: "Beryllium",
    category: "alkaline-earth",
    row: 2,
    col: 2,
    shells: [2, 2],
    facts: {
      discoveredYear: 1798,
      discoveredBy: "Louis-Nicolas Vauquelin",
      usedIn: "Lightweight aerospace parts and X-ray equipment windows.",
      funFact: "Emeralds and aquamarines get their structure from beryllium.",
    },
  },
  {
    number: 5,
    symbol: "B",
    name: "Boron",
    category: "metalloid",
    row: 2,
    col: 13,
    shells: [2, 3],
    facts: {
      discoveredYear: 1808,
      discoveredBy: "Joseph Louis Gay-Lussac & Louis Jacques Thénard",
      usedIn: "Borosilicate glass (like Pyrex) and laundry detergent.",
      funFact: "It's what makes heat-resistant glass able to survive sudden temperature swings.",
    },
  },
  {
    number: 6,
    symbol: "C",
    name: "Carbon",
    category: "nonmetal",
    row: 2,
    col: 14,
    shells: [2, 4],
    facts: {
      discoveredYear: undefined,
      discoveredBy: "Known since antiquity",
      usedIn: "Every living thing on Earth — plus pencils, diamonds, and steel.",
      funFact: "The same element makes up both the softest common mineral (graphite) and the hardest (diamond).",
    },
    quiz: {
      question: "Diamond and the graphite in a pencil are both made of which element?",
      options: ["Carbon", "Silicon", "Iron", "Aluminium"],
      correctIndex: 0,
      hint: "It's the backbone of every living organism on Earth.",
    },
  },
  {
    number: 7,
    symbol: "N",
    name: "Nitrogen",
    category: "nonmetal",
    row: 2,
    col: 15,
    shells: [2, 5],
    facts: {
      discoveredYear: 1772,
      discoveredBy: "Daniel Rutherford",
      usedIn: "Fertilizer production and the air we exhale — it's 78% of Earth's atmosphere.",
      funFact: "Liquid nitrogen is so cold it can flash-freeze a flower solid in seconds.",
    },
    quiz: {
      question: "What gas makes up the largest share of the air you breathe?",
      options: ["Nitrogen", "Oxygen", "Carbon dioxide", "Argon"],
      correctIndex: 0,
      hint: "It's about 78% of the atmosphere — oxygen is only around 21%.",
    },
  },
  {
    number: 8,
    symbol: "O",
    name: "Oxygen",
    category: "nonmetal",
    row: 2,
    col: 16,
    shells: [2, 6],
    facts: {
      discoveredYear: 1774,
      discoveredBy: "Carl Wilhelm Scheele & Joseph Priestley",
      usedIn: "Breathing, combustion, and steel manufacturing.",
      funFact: "Almost half of Earth's crust, by weight, is oxygen bound up in rocks and minerals.",
    },
    quiz: {
      question: "What do humans and most other animals need to breathe to survive?",
      options: ["Oxygen", "Nitrogen", "Helium", "Neon"],
      correctIndex: 0,
      hint: "It's about 21% of the air, and every cell in your body needs it.",
    },
  },
  {
    number: 9,
    symbol: "F",
    name: "Fluorine",
    category: "halogen",
    row: 2,
    col: 17,
    shells: [2, 7],
    facts: {
      discoveredYear: 1886,
      discoveredBy: "Henri Moissan",
      usedIn: "Toothpaste, non-stick cookware coatings, and refrigerants.",
      funFact: "It's the most reactive element on the periodic table — it can even corrode glass.",
    },
    quiz: {
      question: "What common household product contains fluorine to help prevent tooth decay?",
      options: ["Toothpaste", "Dish soap", "Shampoo", "Hand sanitizer"],
      correctIndex: 0,
      hint: "Check the label on the tube in your bathroom.",
    },
  },
  {
    number: 10,
    symbol: "Ne",
    name: "Neon",
    category: "noble-gas",
    row: 2,
    col: 18,
    shells: [2, 8],
    facts: {
      discoveredYear: 1898,
      discoveredBy: "William Ramsay & Morris Travers",
      usedIn: "Glowing signage — its name is basically synonymous with neon signs.",
      funFact: "It barely reacts with anything at all, which is exactly why it glows so cleanly in a tube.",
    },
    quiz: {
      question: "Neon gas is most famous for its use in what?",
      options: ["Glowing signs", "Rocket engines", "Solar panels", "Batteries"],
      correctIndex: 0,
      hint: "Think of a glowing shop window at night.",
    },
  },
  {
    number: 11,
    symbol: "Na",
    name: "Sodium",
    category: "alkali-metal",
    row: 3,
    col: 1,
    shells: [2, 8, 1],
    facts: {
      discoveredYear: 1807,
      discoveredBy: "Humphry Davy",
      usedIn: "Table salt (sodium chloride) and street lighting.",
      funFact: "Pure sodium is so reactive it has to be stored under oil — it reacts violently with water.",
    },
    quiz: {
      question: "Combined with chlorine, sodium forms what everyday kitchen staple?",
      options: ["Table salt", "Sugar", "Baking soda", "Vinegar"],
      correctIndex: 0,
      hint: "You probably have a shaker of it on your table right now.",
    },
  },
  {
    number: 12,
    symbol: "Mg",
    name: "Magnesium",
    category: "alkaline-earth",
    row: 3,
    col: 2,
    shells: [2, 8, 2],
    facts: {
      discoveredYear: 1808,
      discoveredBy: "Humphry Davy",
      usedIn: "Lightweight alloys for laptops, cars, and fireworks' bright white sparks.",
      funFact: "It's essential to chlorophyll — the molecule that makes plants green.",
    },
  },
  {
    number: 13,
    symbol: "Al",
    name: "Aluminium",
    category: "post-transition-metal",
    row: 3,
    col: 13,
    shells: [2, 8, 3],
    facts: {
      discoveredYear: 1825,
      discoveredBy: "Hans Christian Ørsted",
      usedIn: "Drink cans, aircraft bodies, and kitchen foil.",
      funFact: "It was once so hard to refine that it was more valuable than gold or silver.",
    },
    quiz: {
      question: "What common household item is usually made almost entirely of this metal?",
      options: ["A soda can", "A gold ring", "A wooden spoon", "A glass bottle"],
      correctIndex: 0,
      hint: "It's light, doesn't rust, and crushes easily once emptied.",
    },
  },
  {
    number: 14,
    symbol: "Si",
    name: "Silicon",
    category: "metalloid",
    row: 3,
    col: 14,
    shells: [2, 8, 4],
    facts: {
      discoveredYear: 1824,
      discoveredBy: "Jöns Jacob Berzelius",
      usedIn: "Computer chips, solar panels, and ordinary sand and glass.",
      funFact: "The tech industry is nicknamed after it — 'Silicon Valley' — because it's the heart of every microchip.",
    },
    quiz: {
      question: "This element is the basis of nearly every computer chip. Which one is it?",
      options: ["Silicon", "Silver", "Sulfur", "Sodium"],
      correctIndex: 0,
      hint: "A famous California tech hub is named after it.",
    },
  },
  {
    number: 15,
    symbol: "P",
    name: "Phosphorus",
    category: "nonmetal",
    row: 3,
    col: 15,
    shells: [2, 8, 5],
    facts: {
      discoveredYear: 1669,
      discoveredBy: "Hennig Brand",
      usedIn: "Fertilizers, matches, and the DNA in every one of your cells.",
      funFact: "It was discovered by accident while an alchemist was boiling down buckets of urine.",
    },
  },
  {
    number: 16,
    symbol: "S",
    name: "Sulfur",
    category: "nonmetal",
    row: 3,
    col: 16,
    shells: [2, 8, 6],
    facts: {
      discoveredYear: undefined,
      discoveredBy: "Known since antiquity",
      usedIn: "Vulcanizing rubber for tires and manufacturing sulfuric acid.",
      funFact: "Its old name, brimstone, comes straight out of descriptions of volcanoes and fire.",
    },
    quiz: {
      question: "The smell of a struck match is largely due to which element?",
      options: ["Sulfur", "Nitrogen", "Neon", "Boron"],
      correctIndex: 0,
      hint: "It's also the source of the old word 'brimstone'.",
    },
  },
  {
    number: 17,
    symbol: "Cl",
    name: "Chlorine",
    category: "halogen",
    row: 3,
    col: 17,
    shells: [2, 8, 7],
    facts: {
      discoveredYear: 1774,
      discoveredBy: "Carl Wilhelm Scheele",
      usedIn: "Disinfecting drinking water and swimming pools.",
      funFact: "It's a toxic gas on its own, but combined with sodium it becomes harmless table salt.",
    },
    quiz: {
      question: "What is chlorine most commonly used for in everyday life?",
      options: [
        "Disinfecting swimming pools and water",
        "Making rubber tires",
        "Powering batteries",
        "Growing crystals",
      ],
      correctIndex: 0,
      hint: "You can smell it at most public swimming pools.",
    },
  },
  {
    number: 18,
    symbol: "Ar",
    name: "Argon",
    category: "noble-gas",
    row: 3,
    col: 18,
    shells: [2, 8, 8],
    facts: {
      discoveredYear: 1894,
      discoveredBy: "Lord Rayleigh & William Ramsay",
      usedIn: "Filling incandescent and fluorescent light bulbs to stop the filament burning out.",
      funFact: "Its name comes from the Greek for 'lazy' — it barely reacts with anything.",
    },
    quiz: {
      question: "Argon gas is often used inside what everyday object?",
      options: ["Light bulbs", "Car tires", "Drink bottles", "Batteries"],
      correctIndex: 0,
      hint: "It stops the glowing filament inside from burning up too fast.",
    },
  },
  {
    number: 19,
    symbol: "K",
    name: "Potassium",
    category: "alkali-metal",
    row: 4,
    col: 1,
    shells: [2, 8, 8, 1],
    facts: {
      discoveredYear: 1807,
      discoveredBy: "Humphry Davy",
      usedIn: "Fertilizers and, inside your body, keeping your heartbeat regular.",
      funFact: "Bananas are famous for it, but potatoes and beans actually contain even more.",
    },
    quiz: {
      question: "Which fruit is famously associated with this element?",
      options: ["Bananas", "Apples", "Grapes", "Oranges"],
      correctIndex: 0,
      hint: "Its chemical symbol, K, doesn't match its English name — it comes from the Latin 'kalium'.",
    },
  },
  {
    number: 20,
    symbol: "Ca",
    name: "Calcium",
    category: "alkaline-earth",
    row: 4,
    col: 2,
    shells: [2, 8, 8, 2],
    facts: {
      discoveredYear: 1808,
      discoveredBy: "Humphry Davy",
      usedIn: "Bones, teeth, and cement.",
      funFact: "Your skeleton is rebuilding itself with fresh calcium your entire life.",
    },
  },
  {
    number: 21,
    symbol: "Sc",
    name: "Scandium",
    category: "transition-metal",
    row: 4,
    col: 3,
    shells: [2, 8, 9, 2],
    facts: {
      discoveredYear: 1879,
      discoveredBy: "Lars Fredrik Nilson",
      usedIn: "Lightweight aluminium alloys for aerospace and sports gear like baseball bats.",
      funFact: "It was predicted by Mendeleev years before anyone actually found it.",
    },
  },
  {
    number: 22,
    symbol: "Ti",
    name: "Titanium",
    category: "transition-metal",
    row: 4,
    col: 4,
    shells: [2, 8, 10, 2],
    facts: {
      discoveredYear: 1791,
      discoveredBy: "William Gregor",
      usedIn: "Aircraft frames, hip implants, and white paint pigment.",
      funFact: "It's as strong as steel but roughly 45% lighter.",
    },
  },
  {
    number: 23,
    symbol: "V",
    name: "Vanadium",
    category: "transition-metal",
    row: 4,
    col: 5,
    shells: [2, 8, 11, 2],
    facts: {
      discoveredYear: 1801,
      discoveredBy: "Andrés Manuel del Río",
      usedIn: "Strengthening steel for tools and construction beams.",
      funFact: "It's named after Vanadis, a Norse goddess, for its colorful compounds.",
    },
  },
  {
    number: 24,
    symbol: "Cr",
    name: "Chromium",
    category: "transition-metal",
    row: 4,
    col: 6,
    shells: [2, 8, 13, 1],
    facts: {
      discoveredYear: 1797,
      discoveredBy: "Louis Nicolas Vauquelin",
      usedIn: "Stainless steel and the shiny chrome plating on car parts.",
      funFact: "Its name means 'color' in Greek — its compounds range from deep green to fiery orange.",
    },
  },
  {
    number: 25,
    symbol: "Mn",
    name: "Manganese",
    category: "transition-metal",
    row: 4,
    col: 7,
    shells: [2, 8, 13, 2],
    facts: {
      discoveredYear: 1774,
      discoveredBy: "Johan Gottlieb Gahn",
      usedIn: "Strengthening steel and powering alkaline batteries.",
      funFact: "Without it, modern steelmaking as we know it wouldn't exist.",
    },
  },
  {
    number: 26,
    symbol: "Fe",
    name: "Iron",
    category: "transition-metal",
    row: 4,
    col: 8,
    shells: [2, 8, 14, 2],
    facts: {
      discoveredYear: undefined,
      discoveredBy: "Known since antiquity",
      usedIn: "Steel construction, tools, and the hemoglobin that carries oxygen in your blood.",
      funFact: "Earth's core is mostly solid iron — it's why our planet has a magnetic field.",
    },
    quiz: {
      question: "What gives red blood cells the ability to carry oxygen through your body?",
      options: ["Iron in hemoglobin", "Calcium in bones", "Sulfur in skin", "Sodium in plasma"],
      correctIndex: 0,
      hint: "It's the same metal that makes up most of Earth's core.",
    },
  },
  {
    number: 27,
    symbol: "Co",
    name: "Cobalt",
    category: "transition-metal",
    row: 4,
    col: 9,
    shells: [2, 8, 15, 2],
    facts: {
      discoveredYear: 1735,
      discoveredBy: "Georg Brandt",
      usedIn: "Rechargeable battery cathodes and vivid blue glass and ceramics.",
      funFact: "The deep blue in centuries-old porcelain and stained glass is often cobalt.",
    },
  },
  {
    number: 28,
    symbol: "Ni",
    name: "Nickel",
    category: "transition-metal",
    row: 4,
    col: 10,
    shells: [2, 8, 16, 2],
    facts: {
      discoveredYear: 1751,
      discoveredBy: "Axel Fredrik Cronstedt",
      usedIn: "Stainless steel, rechargeable batteries, and coins.",
      funFact: "US 'nickel' coins are actually mostly copper — only 25% nickel.",
    },
  },
  {
    number: 29,
    symbol: "Cu",
    name: "Copper",
    category: "transition-metal",
    row: 4,
    col: 11,
    shells: [2, 8, 18, 1],
    facts: {
      discoveredYear: undefined,
      discoveredBy: "Known since antiquity",
      usedIn: "Electrical wiring, plumbing pipes, and coins.",
      funFact: "It's one of the only metals with a natural color that isn't silvery or golden.",
    },
    quiz: {
      question: "What is copper most commonly used for in modern buildings?",
      options: ["Electrical wiring", "Window glass", "Roof insulation", "Concrete mixing"],
      correctIndex: 0,
      hint: "It conducts electricity extremely well, and has a distinctive reddish color.",
    },
  },
  {
    number: 30,
    symbol: "Zn",
    name: "Zinc",
    category: "transition-metal",
    row: 4,
    col: 12,
    shells: [2, 8, 18, 2],
    facts: {
      discoveredYear: 1746,
      discoveredBy: "Andreas Sigismund Marggraf",
      usedIn: "Galvanizing steel to stop it rusting, and in sunscreen and cold lozenges.",
      funFact: "Mixed with copper, it forms brass — a completely different-looking alloy.",
    },
    quiz: {
      question: "Which metal is coated onto steel to protect it from rust — a process called galvanizing?",
      options: ["Zinc", "Gold", "Lead", "Tin"],
      correctIndex: 0,
      hint: "It's also a common active ingredient in sunscreen and cold remedies.",
    },
  },
  {
    number: 31,
    symbol: "Ga",
    name: "Gallium",
    category: "post-transition-metal",
    row: 4,
    col: 13,
    shells: [2, 8, 18, 3],
    facts: {
      discoveredYear: 1875,
      discoveredBy: "Paul-Émile Lecoq de Boisbaudran",
      usedIn: "LED lights and semiconductor chips.",
      funFact: "It melts at just above room temperature — it can turn to liquid in your hand.",
    },
  },
  {
    number: 32,
    symbol: "Ge",
    name: "Germanium",
    category: "metalloid",
    row: 4,
    col: 14,
    shells: [2, 8, 18, 4],
    facts: {
      discoveredYear: 1886,
      discoveredBy: "Clemens Winkler",
      usedIn: "Fiber-optic cables and infrared camera lenses.",
      funFact: "Mendeleev predicted its exact properties years before it was actually discovered.",
    },
  },
  {
    number: 33,
    symbol: "As",
    name: "Arsenic",
    category: "metalloid",
    row: 4,
    col: 15,
    shells: [2, 8, 18, 5],
    facts: {
      discoveredYear: 1250,
      discoveredBy: "Albertus Magnus",
      usedIn: "Semiconductor manufacturing (in tiny, controlled amounts) and, historically, pest control.",
      funFact: "It's infamous as a poison, but it's also a key ingredient in some LED and laser materials.",
    },
  },
  {
    number: 34,
    symbol: "Se",
    name: "Selenium",
    category: "nonmetal",
    row: 4,
    col: 16,
    shells: [2, 8, 18, 6],
    facts: {
      discoveredYear: 1817,
      discoveredBy: "Jöns Jacob Berzelius",
      usedIn: "Photocopiers, solar cells, and as an essential trace nutrient in your diet.",
      funFact: "It conducts electricity better in the light than in the dark — early photocopiers relied on that.",
    },
  },
  {
    number: 35,
    symbol: "Br",
    name: "Bromine",
    category: "halogen",
    row: 4,
    col: 17,
    shells: [2, 8, 18, 7],
    facts: {
      discoveredYear: 1826,
      discoveredBy: "Antoine Balard",
      usedIn: "Flame retardants and water treatment.",
      funFact: "It's one of only two elements that are liquid at room temperature.",
    },
  },
  {
    number: 36,
    symbol: "Kr",
    name: "Krypton",
    category: "noble-gas",
    row: 4,
    col: 18,
    shells: [2, 8, 18, 8],
    facts: {
      discoveredYear: 1898,
      discoveredBy: "William Ramsay & Morris Travers",
      usedIn: "High-performance camera flashes and some energy-efficient light bulbs.",
      funFact: "Superman's home planet borrowed its name — but real krypton is just a rare, harmless gas.",
    },
  },
  {
    number: 37,
    symbol: "Rb",
    name: "Rubidium",
    category: "alkali-metal",
    row: 5,
    col: 1,
    shells: [2, 8, 18, 8, 1],
    facts: {
      discoveredYear: 1861,
      discoveredBy: "Robert Bunsen & Gustav Kirchhoff",
      usedIn: "Precision atomic clocks and research lasers.",
      funFact: "It was discovered by the same duo who invented the Bunsen burner spectroscope.",
    },
  },
  {
    number: 38,
    symbol: "Sr",
    name: "Strontium",
    category: "alkaline-earth",
    row: 5,
    col: 2,
    shells: [2, 8, 18, 8, 2],
    facts: {
      discoveredYear: 1790,
      discoveredBy: "Adair Crawford",
      usedIn: "Bright red fireworks and some toothpaste for sensitive teeth.",
      funFact: "It's named after Strontian, a small Scottish village where it was first found in ore.",
    },
  },
  {
    number: 39,
    symbol: "Y",
    name: "Yttrium",
    category: "transition-metal",
    row: 5,
    col: 3,
    shells: [2, 8, 18, 9, 2],
    facts: {
      discoveredYear: 1794,
      discoveredBy: "Johan Gadolin",
      usedIn: "Red phosphors in older TV screens and camera lenses.",
      funFact: "It's named after Ytterby, a Swedish village that lent its name to four different elements.",
    },
  },
  {
    number: 40,
    symbol: "Zr",
    name: "Zirconium",
    category: "transition-metal",
    row: 5,
    col: 4,
    shells: [2, 8, 18, 10, 2],
    facts: {
      discoveredYear: 1789,
      discoveredBy: "Martin Heinrich Klaproth",
      usedIn: "Nuclear reactor fuel cladding and heat-resistant ceramics.",
      funFact: "Cubic zirconia, the diamond look-alike gemstone, is made from its oxide.",
    },
  },
  {
    number: 41,
    symbol: "Nb",
    name: "Niobium",
    category: "transition-metal",
    row: 5,
    col: 5,
    shells: [2, 8, 18, 12, 1],
    facts: {
      discoveredYear: 1801,
      discoveredBy: "Charles Hatchett",
      usedIn: "Superconducting magnets and strengthening steel alloys.",
      funFact: "It's named after Niobe, daughter of the mythical king Tantalus — echoing its near-twin element, tantalum.",
    },
  },
  {
    number: 42,
    symbol: "Mo",
    name: "Molybdenum",
    category: "transition-metal",
    row: 5,
    col: 6,
    shells: [2, 8, 18, 13, 1],
    facts: {
      discoveredYear: 1781,
      discoveredBy: "Peter Jacob Hjelm",
      usedIn: "High-strength steel alloys used in drill bits and engine parts.",
      funFact: "It has one of the highest melting points of any element.",
    },
  },
  {
    number: 43,
    symbol: "Tc",
    name: "Technetium",
    category: "transition-metal",
    row: 5,
    col: 7,
    shells: [2, 8, 18, 13, 2],
    facts: {
      discoveredYear: 1937,
      discoveredBy: "Carlo Perrier & Emilio Segrè",
      usedIn: "Medical imaging — it's the most widely used radioactive tracer in hospitals.",
      funFact: "It was the first element ever made artificially rather than found in nature.",
    },
  },
  {
    number: 44,
    symbol: "Ru",
    name: "Ruthenium",
    category: "transition-metal",
    row: 5,
    col: 8,
    shells: [2, 8, 18, 15, 1],
    facts: {
      discoveredYear: 1844,
      discoveredBy: "Karl Ernst Claus",
      usedIn: "Hard-wearing coatings for electrical contacts and fountain pen nibs.",
      funFact: "It's named after Ruthenia, the Latin name for the region around its discoverer's homeland.",
    },
  },
  {
    number: 45,
    symbol: "Rh",
    name: "Rhodium",
    category: "transition-metal",
    row: 5,
    col: 9,
    shells: [2, 8, 18, 16, 1],
    facts: {
      discoveredYear: 1803,
      discoveredBy: "William Hyde Wollaston",
      usedIn: "Catalytic converters in cars and plating white gold jewelry.",
      funFact: "It's one of the rarest and most expensive precious metals — pricier than gold.",
    },
  },
  {
    number: 46,
    symbol: "Pd",
    name: "Palladium",
    category: "transition-metal",
    row: 5,
    col: 10,
    shells: [2, 8, 18, 18],
    facts: {
      discoveredYear: 1803,
      discoveredBy: "William Hyde Wollaston",
      usedIn: "Catalytic converters and electronics.",
      funFact: "It can absorb up to 900 times its own volume of hydrogen gas.",
    },
  },
  {
    number: 47,
    symbol: "Ag",
    name: "Silver",
    category: "transition-metal",
    row: 5,
    col: 11,
    shells: [2, 8, 18, 18, 1],
    facts: {
      discoveredYear: undefined,
      discoveredBy: "Known since antiquity",
      usedIn: "Jewelry, coins, and electrical contacts.",
      funFact: "It's the best electrical and thermal conductor of any metal — better than copper or gold.",
    },
    quiz: {
      question: "Which metal is the best natural conductor of electricity?",
      options: ["Silver", "Iron", "Lead", "Tin"],
      correctIndex: 0,
      hint: "It's a precious metal, often used in jewelry, with a bright white shine.",
    },
  },
  {
    number: 48,
    symbol: "Cd",
    name: "Cadmium",
    category: "transition-metal",
    row: 5,
    col: 12,
    shells: [2, 8, 18, 18, 2],
    facts: {
      discoveredYear: 1817,
      discoveredBy: "Friedrich Stromeyer",
      usedIn: "Rechargeable nickel-cadmium batteries and pigments.",
      funFact: "Its bright yellow-orange pigment was a favorite of painters like Monet and Van Gogh.",
    },
  },
  {
    number: 49,
    symbol: "In",
    name: "Indium",
    category: "post-transition-metal",
    row: 5,
    col: 13,
    shells: [2, 8, 18, 18, 3],
    facts: {
      discoveredYear: 1863,
      discoveredBy: "Ferdinand Reich & Hieronymous Theodor Richter",
      usedIn: "The transparent conductive coating on touchscreens.",
      funFact: "There's a real chance you're touching it right now if you're reading this on a touchscreen.",
    },
  },
  {
    number: 50,
    symbol: "Sn",
    name: "Tin",
    category: "post-transition-metal",
    row: 5,
    col: 14,
    shells: [2, 8, 18, 18, 4],
    facts: {
      discoveredYear: undefined,
      discoveredBy: "Known since antiquity",
      usedIn: "Solder for electronics and tin-plated steel cans.",
      funFact: "Bending a bar of it produces an audible crackle, nicknamed 'tin cry'.",
    },
  },
  {
    number: 51,
    symbol: "Sb",
    name: "Antimony",
    category: "metalloid",
    row: 5,
    col: 15,
    shells: [2, 8, 18, 18, 5],
    facts: {
      discoveredYear: undefined,
      discoveredBy: "Known since antiquity",
      usedIn: "Flame retardants and lead-acid battery grids.",
      funFact: "Ancient Egyptians used one of its minerals, kohl, as eyeliner.",
    },
  },
  {
    number: 52,
    symbol: "Te",
    name: "Tellurium",
    category: "metalloid",
    row: 5,
    col: 16,
    shells: [2, 8, 18, 18, 6],
    facts: {
      discoveredYear: 1782,
      discoveredBy: "Franz-Joseph Müller von Reichenstein",
      usedIn: "Solar panels and alloying with steel and copper.",
      funFact: "In tiny doses it can make a person's breath smell like garlic for weeks.",
    },
  },
  {
    number: 53,
    symbol: "I",
    name: "Iodine",
    category: "halogen",
    row: 5,
    col: 17,
    shells: [2, 8, 18, 18, 7],
    facts: {
      discoveredYear: 1811,
      discoveredBy: "Bernard Courtois",
      usedIn: "Iodized table salt and disinfecting wounds.",
      funFact: "Your thyroid gland needs it — a deficiency is why salt is often iodized.",
    },
  },
  {
    number: 54,
    symbol: "Xe",
    name: "Xenon",
    category: "noble-gas",
    row: 5,
    col: 18,
    shells: [2, 8, 18, 18, 8],
    facts: {
      discoveredYear: 1898,
      discoveredBy: "William Ramsay & Morris Travers",
      usedIn: "High-intensity car headlights and ion propulsion for spacecraft.",
      funFact: "Its name means 'stranger' in Greek — it's one of the rarest gases in Earth's atmosphere.",
    },
  },
  {
    number: 55,
    symbol: "Cs",
    name: "Caesium",
    category: "alkali-metal",
    row: 6,
    col: 1,
    shells: [2, 8, 18, 18, 8, 1],
    facts: {
      discoveredYear: 1860,
      discoveredBy: "Robert Bunsen & Gustav Kirchhoff",
      usedIn: "Atomic clocks — the official length of a second is defined using it.",
      funFact: "It's so reactive it explodes on contact with water more violently than sodium or potassium.",
    },
  },
  {
    number: 56,
    symbol: "Ba",
    name: "Barium",
    category: "alkaline-earth",
    row: 6,
    col: 2,
    shells: [2, 8, 18, 18, 8, 2],
    facts: {
      discoveredYear: 1808,
      discoveredBy: "Humphry Davy",
      usedIn: "The 'barium meal' drink that makes soft tissue visible on medical X-rays.",
      funFact: "Its compounds burn with a vivid green flame, used in fireworks.",
    },
  },
  {
    number: 57,
    symbol: "La",
    name: "Lanthanum",
    category: "lanthanide",
    row: 8,
    col: 3,
    shells: [2, 8, 18, 18, 9, 2],
    facts: {
      discoveredYear: 1839,
      discoveredBy: "Carl Gustaf Mosander",
      usedIn: "Camera and telescope lenses, and hybrid-car battery electrodes.",
      funFact: "The entire 'lanthanide' row of the table is named after it.",
    },
  },
  {
    number: 58,
    symbol: "Ce",
    name: "Cerium",
    category: "lanthanide",
    row: 8,
    col: 4,
    shells: [2, 8, 18, 20, 8, 2],
    facts: {
      discoveredYear: 1803,
      discoveredBy: "Jöns Jacob Berzelius & Wilhelm Hisinger",
      usedIn: "Self-cleaning ovens and glass polishing.",
      funFact: "It's the most abundant of all the rare-earth elements — not actually rare at all.",
    },
  },
  {
    number: 59,
    symbol: "Pr",
    name: "Praseodymium",
    category: "lanthanide",
    row: 8,
    col: 5,
    shells: [2, 8, 18, 21, 8, 2],
    facts: {
      discoveredYear: 1885,
      discoveredBy: "Carl Auer von Welsbach",
      usedIn: "Strong permanent magnets and yellow glass tinting for welders' goggles.",
      funFact: "Its name means 'green twin' in Greek, describing the color of its salts.",
    },
  },
  {
    number: 60,
    symbol: "Nd",
    name: "Neodymium",
    category: "lanthanide",
    row: 8,
    col: 6,
    shells: [2, 8, 18, 22, 8, 2],
    facts: {
      discoveredYear: 1885,
      discoveredBy: "Carl Auer von Welsbach",
      usedIn: "The strongest permanent magnets known — used in headphones and hard drives.",
      funFact: "A neodymium magnet the size of a coin can lift many times its own weight in steel.",
    },
  },
  {
    number: 61,
    symbol: "Pm",
    name: "Promethium",
    category: "lanthanide",
    row: 8,
    col: 7,
    shells: [2, 8, 18, 23, 8, 2],
    facts: {
      discoveredYear: 1945,
      discoveredBy: "Jacob A. Marinsky, Lawrence E. Glendenin & Charles D. Coryell",
      usedIn: "Luminous paint and nuclear-powered space probe batteries.",
      funFact: "It's named after Prometheus, the Titan who stole fire — fitting for a radioactive glow-in-the-dark element.",
    },
  },
  {
    number: 62,
    symbol: "Sm",
    name: "Samarium",
    category: "lanthanide",
    row: 8,
    col: 8,
    shells: [2, 8, 18, 24, 8, 2],
    facts: {
      discoveredYear: 1879,
      discoveredBy: "Paul-Émile Lecoq de Boisbaudran",
      usedIn: "High-strength magnets that stay magnetic at high temperatures.",
      funFact: "It was the first element ever named after a person — mine official Vasili Samarsky-Bykhovets.",
    },
  },
  {
    number: 63,
    symbol: "Eu",
    name: "Europium",
    category: "lanthanide",
    row: 8,
    col: 9,
    shells: [2, 8, 18, 25, 8, 2],
    facts: {
      discoveredYear: 1901,
      discoveredBy: "Eugène-Anatole Demarçay",
      usedIn: "The red phosphors in TV and phone screens, and anti-counterfeiting ink on euro banknotes.",
      funFact: "It's literally named after the continent of Europe.",
    },
  },
  {
    number: 64,
    symbol: "Gd",
    name: "Gadolinium",
    category: "lanthanide",
    row: 8,
    col: 10,
    shells: [2, 8, 18, 25, 9, 2],
    facts: {
      discoveredYear: 1880,
      discoveredBy: "Jean Charles Galissard de Marignac",
      usedIn: "The contrast agent injected before some MRI scans.",
      funFact: "It's named after Johan Gadolin, the chemist who kicked off the rare-earth element hunt.",
    },
  },
  {
    number: 65,
    symbol: "Tb",
    name: "Terbium",
    category: "lanthanide",
    row: 8,
    col: 11,
    shells: [2, 8, 18, 27, 8, 2],
    facts: {
      discoveredYear: 1843,
      discoveredBy: "Carl Gustaf Mosander",
      usedIn: "Green phosphors in energy-efficient lighting.",
      funFact: "It's one of four elements named after the same tiny Swedish village, Ytterby.",
    },
  },
  {
    number: 66,
    symbol: "Dy",
    name: "Dysprosium",
    category: "lanthanide",
    row: 8,
    col: 12,
    shells: [2, 8, 18, 28, 8, 2],
    facts: {
      discoveredYear: 1886,
      discoveredBy: "Paul-Émile Lecoq de Boisbaudran",
      usedIn: "Boosting the heat resistance of neodymium magnets in electric motors.",
      funFact: "Its name comes from the Greek for 'hard to get' — it took its discoverer over 30 attempts to isolate.",
    },
  },
  {
    number: 67,
    symbol: "Ho",
    name: "Holmium",
    category: "lanthanide",
    row: 8,
    col: 13,
    shells: [2, 8, 18, 29, 8, 2],
    facts: {
      discoveredYear: 1878,
      discoveredBy: "Marc Delafontaine & Jacques-Louis Soret",
      usedIn: "Medical and industrial lasers used in surgery.",
      funFact: "It has the highest magnetic strength of any naturally occurring element.",
    },
  },
  {
    number: 68,
    symbol: "Er",
    name: "Erbium",
    category: "lanthanide",
    row: 8,
    col: 14,
    shells: [2, 8, 18, 30, 8, 2],
    facts: {
      discoveredYear: 1843,
      discoveredBy: "Carl Gustaf Mosander",
      usedIn: "Amplifying signals in fiber-optic internet cables.",
      funFact: "It's the fourth (and last) element named after the village of Ytterby.",
    },
  },
  {
    number: 69,
    symbol: "Tm",
    name: "Thulium",
    category: "lanthanide",
    row: 8,
    col: 15,
    shells: [2, 8, 18, 31, 8, 2],
    facts: {
      discoveredYear: 1879,
      discoveredBy: "Per Teodor Cleve",
      usedIn: "Portable X-ray devices and some surgical lasers.",
      funFact: "It's the rarest of all naturally occurring lanthanides, but still far from the rarest element overall.",
    },
  },
  {
    number: 70,
    symbol: "Yb",
    name: "Ytterbium",
    category: "lanthanide",
    row: 8,
    col: 16,
    shells: [2, 8, 18, 32, 8, 2],
    facts: {
      discoveredYear: 1878,
      discoveredBy: "Jean Charles Galissard de Marignac",
      usedIn: "Some of the most precise atomic clocks ever built.",
      funFact: "It's the third element named after Ytterby — that one village has quite a legacy.",
    },
  },
  {
    number: 71,
    symbol: "Lu",
    name: "Lutetium",
    category: "lanthanide",
    row: 8,
    col: 17,
    shells: [2, 8, 18, 32, 9, 2],
    facts: {
      discoveredYear: 1907,
      discoveredBy: "Georges Urbain",
      usedIn: "Detector crystals in PET medical scanners.",
      funFact: "It's named after Lutetia, the old Roman name for Paris.",
    },
  },
  {
    number: 72,
    symbol: "Hf",
    name: "Hafnium",
    category: "transition-metal",
    row: 6,
    col: 4,
    shells: [2, 8, 18, 32, 10, 2],
    facts: {
      discoveredYear: 1923,
      discoveredBy: "Dirk Coster & George de Hevesy",
      usedIn: "Control rods in nuclear reactors and computer chip components.",
      funFact: "It's named after Hafnia, the Latin name for Copenhagen, where it was discovered.",
    },
  },
  {
    number: 73,
    symbol: "Ta",
    name: "Tantalum",
    category: "transition-metal",
    row: 6,
    col: 5,
    shells: [2, 8, 18, 32, 11, 2],
    facts: {
      discoveredYear: 1802,
      discoveredBy: "Anders Gustaf Ekeberg",
      usedIn: "Tiny capacitors inside smartphones and laptops.",
      funFact: "It's named after the mythical King Tantalus, since it resisted acid so stubbornly it was 'tantalizing' to dissolve.",
    },
  },
  {
    number: 74,
    symbol: "W",
    name: "Tungsten",
    category: "transition-metal",
    row: 6,
    col: 6,
    shells: [2, 8, 18, 32, 12, 2],
    facts: {
      discoveredYear: 1783,
      discoveredBy: "Juan José Elhuyar & Fausto Elhuyar",
      usedIn: "Light bulb filaments and drill bit tips.",
      funFact: "It has the highest melting point of any metal — nearly 3,400°C.",
    },
  },
  {
    number: 75,
    symbol: "Re",
    name: "Rhenium",
    category: "transition-metal",
    row: 6,
    col: 7,
    shells: [2, 8, 18, 32, 13, 2],
    facts: {
      discoveredYear: 1925,
      discoveredBy: "Walter Noddack, Ida Tacke & Otto Berg",
      usedIn: "Jet engine turbine blades that must survive extreme heat.",
      funFact: "It was one of the very last stable elements to be discovered.",
    },
  },
  {
    number: 76,
    symbol: "Os",
    name: "Osmium",
    category: "transition-metal",
    row: 6,
    col: 8,
    shells: [2, 8, 18, 32, 14, 2],
    facts: {
      discoveredYear: 1803,
      discoveredBy: "Smithson Tennant",
      usedIn: "Extremely hard-wearing fountain pen nib tips and electrical contacts.",
      funFact: "It's the densest naturally occurring element on Earth.",
    },
  },
  {
    number: 77,
    symbol: "Ir",
    name: "Iridium",
    category: "transition-metal",
    row: 6,
    col: 9,
    shells: [2, 8, 18, 32, 15, 2],
    facts: {
      discoveredYear: 1803,
      discoveredBy: "Smithson Tennant",
      usedIn: "Spark plug electrodes and the standard kilogram's old reference cylinder.",
      funFact: "A thin layer of it found worldwide in rock strata helped prove an asteroid killed the dinosaurs.",
    },
  },
  {
    number: 78,
    symbol: "Pt",
    name: "Platinum",
    category: "transition-metal",
    row: 6,
    col: 10,
    shells: [2, 8, 18, 32, 17, 1],
    facts: {
      discoveredYear: 1735,
      discoveredBy: "Antonio de Ulloa",
      usedIn: "Catalytic converters, jewelry, and lab equipment.",
      funFact: "It's rarer than gold — all the platinum ever mined would fit in an average living room.",
    },
  },
  {
    number: 79,
    symbol: "Au",
    name: "Gold",
    category: "transition-metal",
    row: 6,
    col: 11,
    shells: [2, 8, 18, 32, 18, 1],
    facts: {
      discoveredYear: undefined,
      discoveredBy: "Known since antiquity",
      usedIn: "Jewelry, electronics connectors, and as a store of wealth for millennia.",
      funFact: "Nearly all the gold on Earth arrived from collisions between neutron stars, long before our planet formed.",
    },
    quiz: {
      question: "What made this element valuable enough to become a global currency standard for centuries?",
      options: [
        "It doesn't tarnish or corrode",
        "It's the lightest metal",
        "It conducts electricity poorly",
        "It's magnetic",
      ],
      correctIndex: 0,
      hint: "Ancient coins and jewelry made of it still look untarnished thousands of years later.",
    },
  },
  {
    number: 80,
    symbol: "Hg",
    name: "Mercury",
    category: "transition-metal",
    row: 6,
    col: 12,
    shells: [2, 8, 18, 32, 18, 2],
    facts: {
      discoveredYear: undefined,
      discoveredBy: "Known since antiquity",
      usedIn: "Old-style glass thermometers and some fluorescent lighting.",
      funFact: "It's the only metal that's liquid at room temperature — named after the fast-moving Roman god.",
    },
    quiz: {
      question: "What is unique about this element compared to almost every other metal?",
      options: [
        "It's liquid at room temperature",
        "It's the lightest known metal",
        "It doesn't conduct electricity",
        "It's completely transparent",
      ],
      correctIndex: 0,
      hint: "Old thermometers used a silvery liquid that rolled around if the glass broke — that was this.",
    },
  },
  {
    number: 81,
    symbol: "Tl",
    name: "Thallium",
    category: "post-transition-metal",
    row: 6,
    col: 13,
    shells: [2, 8, 18, 32, 18, 3],
    facts: {
      discoveredYear: 1861,
      discoveredBy: "William Crookes",
      usedIn: "Infrared optical equipment and some specialized glass.",
      funFact: "It was once nicknamed 'the poisoner's poison' for being tasteless, odorless, and once hard to detect.",
    },
  },
  {
    number: 82,
    symbol: "Pb",
    name: "Lead",
    category: "post-transition-metal",
    row: 6,
    col: 14,
    shells: [2, 8, 18, 32, 18, 4],
    facts: {
      discoveredYear: undefined,
      discoveredBy: "Known since antiquity",
      usedIn: "Car batteries and radiation shielding.",
      funFact: "The Romans used it for water pipes — the word 'plumbing' comes from plumbum, its Latin name.",
    },
  },
  {
    number: 83,
    symbol: "Bi",
    name: "Bismuth",
    category: "post-transition-metal",
    row: 6,
    col: 15,
    shells: [2, 8, 18, 32, 18, 5],
    facts: {
      discoveredYear: 1753,
      discoveredBy: "Claude François Geoffroy",
      usedIn: "The active ingredient in some stomach-upset medicines, and rainbow-hued crystal displays.",
      funFact: "When it cools from a melt, it grows into stunning iridescent, staircase-shaped crystals.",
    },
  },
  {
    number: 84,
    symbol: "Po",
    name: "Polonium",
    category: "post-transition-metal",
    row: 6,
    col: 16,
    shells: [2, 8, 18, 32, 18, 6],
    facts: {
      discoveredYear: 1898,
      discoveredBy: "Marie Curie & Pierre Curie",
      usedIn: "Removing static electricity in specialized industrial equipment.",
      funFact: "Marie Curie named it after her homeland, Poland, to draw attention to its lack of independence at the time.",
    },
  },
  {
    number: 85,
    symbol: "At",
    name: "Astatine",
    category: "halogen",
    row: 6,
    col: 17,
    shells: [2, 8, 18, 32, 18, 7],
    facts: {
      discoveredYear: 1940,
      discoveredBy: "Dale R. Corson, Kenneth Ross MacKenzie & Emilio Segrè",
      usedIn: "Experimental targeted cancer radiotherapy research.",
      funFact: "It's so rare that at any moment, only about one gram of it exists naturally on all of Earth.",
    },
  },
  {
    number: 86,
    symbol: "Rn",
    name: "Radon",
    category: "noble-gas",
    row: 6,
    col: 18,
    shells: [2, 8, 18, 32, 18, 8],
    facts: {
      discoveredYear: 1900,
      discoveredBy: "Friedrich Ernst Dorn",
      usedIn: "Once used in early radiation therapy; today it's mainly a home-safety concern.",
      funFact: "It seeps up from the ground naturally, which is why homes in some regions test for it.",
    },
  },
  {
    number: 87,
    symbol: "Fr",
    name: "Francium",
    category: "alkali-metal",
    row: 7,
    col: 1,
    shells: [2, 8, 18, 32, 18, 8, 1],
    facts: {
      discoveredYear: 1939,
      discoveredBy: "Marguerite Perey",
      usedIn: "Almost nothing — it decays away within minutes of forming.",
      funFact: "It's so unstable that less than one ounce likely exists on Earth at any given moment.",
    },
  },
  {
    number: 88,
    symbol: "Ra",
    name: "Radium",
    category: "alkaline-earth",
    row: 7,
    col: 2,
    shells: [2, 8, 18, 32, 18, 8, 2],
    facts: {
      discoveredYear: 1898,
      discoveredBy: "Marie Curie & Pierre Curie",
      usedIn: "Once used in glow-in-the-dark watch dials, now avoided due to its radioactivity.",
      funFact: "Its glow made it a sensation in the early 1900s, before its dangers were understood.",
    },
  },
  {
    number: 89,
    symbol: "Ac",
    name: "Actinium",
    category: "actinide",
    row: 9,
    col: 3,
    shells: [2, 8, 18, 32, 18, 9, 2],
    facts: {
      discoveredYear: 1899,
      discoveredBy: "André-Louis Debierne",
      usedIn: "Experimental targeted cancer treatments.",
      funFact: "It glows faintly blue in the dark, and gives the whole actinide row its name.",
    },
  },
  {
    number: 90,
    symbol: "Th",
    name: "Thorium",
    category: "actinide",
    row: 9,
    col: 4,
    shells: [2, 8, 18, 32, 18, 10, 2],
    facts: {
      discoveredYear: 1829,
      discoveredBy: "Jöns Jacob Berzelius",
      usedIn: "Researched as a safer alternative nuclear reactor fuel to uranium.",
      funFact: "It's named after Thor, the Norse god of thunder.",
    },
  },
  {
    number: 91,
    symbol: "Pa",
    name: "Protactinium",
    category: "actinide",
    row: 9,
    col: 5,
    shells: [2, 8, 18, 32, 20, 9, 2],
    facts: {
      discoveredYear: 1913,
      discoveredBy: "Kasimir Fajans & Oswald Helmuth Göhring",
      usedIn: "Almost exclusively scientific research — it's extremely rare and highly radioactive.",
      funFact: "Its name means 'before actinium', because it decays into actinium.",
    },
  },
  {
    number: 92,
    symbol: "U",
    name: "Uranium",
    category: "actinide",
    row: 9,
    col: 6,
    shells: [2, 8, 18, 32, 21, 9, 2],
    facts: {
      discoveredYear: 1789,
      discoveredBy: "Martin Heinrich Klaproth",
      usedIn: "Fuel for nuclear power plants.",
      funFact: "It was named after the planet Uranus, which had been discovered just eight years earlier.",
    },
    quiz: {
      question: "What is uranium primarily used for today?",
      options: [
        "Fuel for nuclear power plants",
        "Coating cooking pans",
        "Making glass unbreakable",
        "Flavoring food",
      ],
      correctIndex: 0,
      hint: "Its atoms can be split apart to release enormous amounts of energy.",
    },
  },
  {
    number: 93,
    symbol: "Np",
    name: "Neptunium",
    category: "actinide",
    row: 9,
    col: 7,
    shells: [2, 8, 18, 32, 22, 9, 2],
    facts: {
      discoveredYear: 1940,
      discoveredBy: "Edwin McMillan & Philip H. Abelson",
      usedIn: "Almost entirely scientific research and some neutron-detection instruments.",
      funFact: "It was the first artificial element made that doesn't occur in usable quantities in nature.",
    },
  },
  {
    number: 94,
    symbol: "Pu",
    name: "Plutonium",
    category: "actinide",
    row: 9,
    col: 8,
    shells: [2, 8, 18, 32, 24, 8, 2],
    facts: {
      discoveredYear: 1940,
      discoveredBy: "Glenn T. Seaborg and team",
      usedIn: "Nuclear reactor fuel and power sources for deep-space probes.",
      funFact: "It powers the Voyager and Curiosity Mars rover missions, decades after launch.",
    },
  },
  {
    number: 95,
    symbol: "Am",
    name: "Americium",
    category: "actinide",
    row: 9,
    col: 9,
    shells: [2, 8, 18, 32, 25, 8, 2],
    facts: {
      discoveredYear: 1944,
      discoveredBy: "Glenn T. Seaborg and team",
      usedIn: "The radioactive source inside most household smoke detectors.",
      funFact: "There's a tiny, safely sealed amount in nearly every smoke alarm in the world.",
    },
  },
  {
    number: 96,
    symbol: "Cm",
    name: "Curium",
    category: "actinide",
    row: 9,
    col: 10,
    shells: [2, 8, 18, 32, 25, 9, 2],
    facts: {
      discoveredYear: 1944,
      discoveredBy: "Glenn T. Seaborg and team",
      usedIn: "Scientific instruments aboard Mars rovers that analyze rock composition.",
      funFact: "It's named after Marie and Pierre Curie, the pioneering radioactivity researchers.",
    },
  },
  {
    number: 97,
    symbol: "Bk",
    name: "Berkelium",
    category: "actinide",
    row: 9,
    col: 11,
    shells: [2, 8, 18, 32, 27, 8, 2],
    facts: {
      discoveredYear: 1949,
      discoveredBy: "Glenn T. Seaborg and team",
      usedIn: "Purely scientific research into superheavy element synthesis.",
      funFact: "It's named after Berkeley, California, where it was first created.",
    },
  },
  {
    number: 98,
    symbol: "Cf",
    name: "Californium",
    category: "actinide",
    row: 9,
    col: 12,
    shells: [2, 8, 18, 32, 28, 8, 2],
    facts: {
      discoveredYear: 1950,
      discoveredBy: "Glenn T. Seaborg and team",
      usedIn: "Portable neutron sources for detecting metals and starting nuclear reactors.",
      funFact: "A microgram of it releases so many neutrons it can be used to help locate gold and silver ore.",
    },
  },
  {
    number: 99,
    symbol: "Es",
    name: "Einsteinium",
    category: "actinide",
    row: 9,
    col: 13,
    shells: [2, 8, 18, 32, 29, 8, 2],
    facts: {
      discoveredYear: 1952,
      discoveredBy: "Researchers analyzing the first hydrogen bomb test debris",
      usedIn: "Purely scientific research — none exists in usable quantities.",
      funFact: "It was discovered hidden in the fallout of the first hydrogen bomb test.",
    },
  },
  {
    number: 100,
    symbol: "Fm",
    name: "Fermium",
    category: "actinide",
    row: 9,
    col: 14,
    shells: [2, 8, 18, 32, 30, 8, 2],
    facts: {
      discoveredYear: 1952,
      discoveredBy: "Researchers analyzing the first hydrogen bomb test debris",
      usedIn: "Purely scientific research into atomic structure.",
      funFact: "It's named after Enrico Fermi, who built the world's first nuclear reactor.",
    },
  },
  {
    number: 101,
    symbol: "Md",
    name: "Mendelevium",
    category: "actinide",
    row: 9,
    col: 15,
    shells: [2, 8, 18, 32, 31, 8, 2],
    facts: {
      discoveredYear: 1955,
      discoveredBy: "Glenn T. Seaborg and team",
      usedIn: "Purely scientific research — made one atom at a time.",
      funFact: "It's named after Dmitri Mendeleev, the chemist who first arranged the periodic table.",
    },
  },
  {
    number: 102,
    symbol: "No",
    name: "Nobelium",
    category: "actinide",
    row: 9,
    col: 16,
    shells: [2, 8, 18, 32, 32, 8, 2],
    facts: {
      discoveredYear: 1958,
      discoveredBy: "Researchers at the Nobel Institute",
      usedIn: "Purely scientific research into atomic behavior.",
      funFact: "It's named after Alfred Nobel, the inventor of dynamite and founder of the Nobel Prizes.",
    },
  },
  {
    number: 103,
    symbol: "Lr",
    name: "Lawrencium",
    category: "actinide",
    row: 9,
    col: 17,
    shells: [2, 8, 18, 32, 32, 8, 3],
    facts: {
      discoveredYear: 1961,
      discoveredBy: "Albert Ghiorso and team",
      usedIn: "Purely scientific research — the final element of the actinide row.",
      funFact: "It's named after Ernest Lawrence, inventor of the particle accelerator that made discovering it possible.",
    },
  },
  {
    number: 104,
    symbol: "Rf",
    name: "Rutherfordium",
    category: "transition-metal",
    row: 7,
    col: 4,
    shells: [2, 8, 18, 32, 32, 10, 2],
    facts: {
      discoveredYear: 1969,
      discoveredBy: "Researchers at Berkeley and Dubna",
      usedIn: "Purely scientific research — made only a few atoms at a time.",
      funFact: "It's named after Ernest Rutherford, who discovered the atomic nucleus.",
    },
  },
  {
    number: 105,
    symbol: "Db",
    name: "Dubnium",
    category: "transition-metal",
    row: 7,
    col: 5,
    shells: [2, 8, 18, 32, 32, 11, 2],
    facts: {
      discoveredYear: 1970,
      discoveredBy: "Researchers at Berkeley and Dubna",
      usedIn: "Purely scientific research into superheavy elements.",
      funFact: "It's named after Dubna, Russia, home to one of the labs that helped create it.",
    },
  },
  {
    number: 106,
    symbol: "Sg",
    name: "Seaborgium",
    category: "transition-metal",
    row: 7,
    col: 6,
    shells: [2, 8, 18, 32, 32, 12, 2],
    facts: {
      discoveredYear: 1974,
      discoveredBy: "Researchers at Berkeley",
      usedIn: "Purely scientific research — never made in more than a handful of atoms.",
      funFact: "It's one of the few elements named after someone who was still alive at the time — Glenn Seaborg.",
    },
  },
  {
    number: 107,
    symbol: "Bh",
    name: "Bohrium",
    category: "transition-metal",
    row: 7,
    col: 7,
    shells: [2, 8, 18, 32, 32, 13, 2],
    facts: {
      discoveredYear: 1981,
      discoveredBy: "Researchers at GSI Darmstadt, Germany",
      usedIn: "Purely scientific research.",
      funFact: "It's named after physicist Niels Bohr, whose atomic model inspired this game's atom view.",
    },
  },
  {
    number: 108,
    symbol: "Hs",
    name: "Hassium",
    category: "transition-metal",
    row: 7,
    col: 8,
    shells: [2, 8, 18, 32, 32, 14, 2],
    facts: {
      discoveredYear: 1984,
      discoveredBy: "Researchers at GSI Darmstadt, Germany",
      usedIn: "Purely scientific research.",
      funFact: "It's named after Hesse, the German state where it was first created.",
    },
  },
  {
    number: 109,
    symbol: "Mt",
    name: "Meitnerium",
    category: "transition-metal",
    row: 7,
    col: 9,
    shells: [2, 8, 18, 32, 32, 15, 2],
    facts: {
      discoveredYear: 1982,
      discoveredBy: "Researchers at GSI Darmstadt, Germany",
      usedIn: "Purely scientific research.",
      funFact: "It's named after Lise Meitner, the physicist who helped explain nuclear fission.",
    },
  },
  {
    number: 110,
    symbol: "Ds",
    name: "Darmstadtium",
    category: "transition-metal",
    row: 7,
    col: 10,
    shells: [2, 8, 18, 32, 32, 17, 1],
    facts: {
      discoveredYear: 1994,
      discoveredBy: "Researchers at GSI Darmstadt, Germany",
      usedIn: "Purely scientific research.",
      funFact: "It's named after Darmstadt, the German city where the lab that created it is based.",
    },
  },
  {
    number: 111,
    symbol: "Rg",
    name: "Roentgenium",
    category: "transition-metal",
    row: 7,
    col: 11,
    shells: [2, 8, 18, 32, 32, 18, 1],
    facts: {
      discoveredYear: 1994,
      discoveredBy: "Researchers at GSI Darmstadt, Germany",
      usedIn: "Purely scientific research.",
      funFact: "It's named after Wilhelm Röntgen, who discovered X-rays.",
    },
  },
  {
    number: 112,
    symbol: "Cn",
    name: "Copernicium",
    category: "transition-metal",
    row: 7,
    col: 12,
    shells: [2, 8, 18, 32, 32, 18, 2],
    facts: {
      discoveredYear: 1996,
      discoveredBy: "Researchers at GSI Darmstadt, Germany",
      usedIn: "Purely scientific research.",
      funFact: "It's named after the astronomer Nicolaus Copernicus.",
    },
  },
  {
    number: 113,
    symbol: "Nh",
    name: "Nihonium",
    category: "post-transition-metal",
    row: 7,
    col: 13,
    shells: [2, 8, 18, 32, 32, 18, 3],
    facts: {
      discoveredYear: 2004,
      discoveredBy: "Researchers at RIKEN, Japan",
      usedIn: "Purely scientific research.",
      funFact: "It was the first element discovered and named in Asia — 'Nihon' is Japanese for Japan.",
    },
  },
  {
    number: 114,
    symbol: "Fl",
    name: "Flerovium",
    category: "post-transition-metal",
    row: 7,
    col: 14,
    shells: [2, 8, 18, 32, 32, 18, 4],
    facts: {
      discoveredYear: 1998,
      discoveredBy: "Researchers at Dubna, Russia",
      usedIn: "Purely scientific research.",
      funFact: "It's named after Georgy Flyorov, founder of the Dubna nuclear research lab.",
    },
  },
  {
    number: 115,
    symbol: "Mc",
    name: "Moscovium",
    category: "post-transition-metal",
    row: 7,
    col: 15,
    shells: [2, 8, 18, 32, 32, 18, 5],
    facts: {
      discoveredYear: 2003,
      discoveredBy: "Researchers at Dubna, Russia",
      usedIn: "Purely scientific research.",
      funFact: "It's named after the Moscow region, home to the lab that helped create it.",
    },
  },
  {
    number: 116,
    symbol: "Lv",
    name: "Livermorium",
    category: "post-transition-metal",
    row: 7,
    col: 16,
    shells: [2, 8, 18, 32, 32, 18, 6],
    facts: {
      discoveredYear: 2000,
      discoveredBy: "Researchers at Dubna and Livermore",
      usedIn: "Purely scientific research.",
      funFact: "It's named after the Lawrence Livermore National Laboratory in California.",
    },
  },
  {
    number: 117,
    symbol: "Ts",
    name: "Tennessine",
    category: "halogen",
    row: 7,
    col: 17,
    shells: [2, 8, 18, 32, 32, 18, 7],
    facts: {
      discoveredYear: 2010,
      discoveredBy: "Researchers at Dubna, Oak Ridge, and Vanderbilt",
      usedIn: "Purely scientific research.",
      funFact: "It's named after the state of Tennessee, home to the Oak Ridge lab that helped make it.",
    },
  },
  {
    number: 118,
    symbol: "Og",
    name: "Oganesson",
    category: "noble-gas",
    row: 7,
    col: 18,
    shells: [2, 8, 18, 32, 32, 18, 8],
    facts: {
      discoveredYear: 2002,
      discoveredBy: "Researchers at Dubna, Russia",
      usedIn: "Purely scientific research — the heaviest element ever made.",
      funFact: "It's the only element named after a living scientist honored during their own lifetime: Yuri Oganessian.",
    },
  },
];

export const ELEMENT_BY_NUMBER: Map<number, ElementDef> = new Map(
  ELEMENTS.map((el) => [el.number, el])
);

export const TOTAL_ELEMENTS = ELEMENTS.length;

export const CATEGORY_LABELS: Record<ElementDef["category"], string> = {
  "alkali-metal": "Alkali metal",
  "alkaline-earth": "Alkaline earth metal",
  "transition-metal": "Transition metal",
  "post-transition-metal": "Post-transition metal",
  metalloid: "Metalloid",
  nonmetal: "Nonmetal",
  halogen: "Halogen",
  "noble-gas": "Noble gas",
  lanthanide: "Lanthanide",
  actinide: "Actinide",
};

/** Soft category tint, used sparingly as a single inner-glow accent per tile. */
export const CATEGORY_TINTS: Record<ElementDef["category"], string> = {
  "alkali-metal": "#E8917A",
  "alkaline-earth": "#E0A868",
  "transition-metal": "#C9A961",
  "post-transition-metal": "#D4B483",
  metalloid: "#9CAF88",
  nonmetal: "#7FA8C9",
  halogen: "#6FB3A8",
  "noble-gas": "#A78BC9",
  lanthanide: "#D98BA0",
  actinide: "#C26B8C",
};

export const CATEGORIES: ElementDef["category"][] = [
  "alkali-metal",
  "alkaline-earth",
  "transition-metal",
  "post-transition-metal",
  "metalloid",
  "nonmetal",
  "halogen",
  "noble-gas",
  "lanthanide",
  "actinide",
];
